[package]
name = "ringest-fs"
version = "0.1.0"
edition = "2024"

[features]
regex = ["dep:regex"]
default = ["regex"]

[dependencies]
dashmap = "6.1.0"
regex = { version = "1.12.3", optional = true }
