[package]
name = "ringest-error"
version = "0.1.0"
edition = "2024"

[features]
regex = ["dep:regex"]

[dependencies]
regex = { version = "1.12.3", optional = true }
thiserror = "2.0.18"
tokio = "1.49.0"
